### ISSUE TITLE
error while running: "cannot read propery "allowed_users" of undefined

### ISSUE THREAD

**Issue by davehamer** [TimH96/anti-burner-bot#1]
Hiya,

![image](https://user-images.githubusercontent.com/8375536/128074578-68934c40-aed7-4a91-81be-1c597aac515d.png)

Followed readme.md - and this was the output when connected and a new account joins

no ban occurs.

**Comment by davehamer** [comment]
Did a bit of debugging - I don't know typescript but I do know javascript.
It appears you have some issues with the "channel" variables - they simply don't exist.
https://github.com/TimH96/anti-burner-bot/blob/8b9a2b3f7b1ef93357d18da709da40a701e7271f/src/bot.ts#L72
This seems to cause it to exit prematurely, so I changed this into a console.log
Next problem is the min_age variable:
https://github.com/TimH96/anti-burner-bot/blob/8b9a2b3f7b1ef93357d18da709da40a701e7271f/src/bot.ts#L79
I set this manually to 86400
Next issue is the "ban_reason"
https://github.com/TimH96/anti-burner-bot/blob/8b9a2b3f7b1ef93357d18da709da40a701e7271f/src/bot.ts#L81

again, manually setting this has sorted it.

If you can fixup the channel variable reading then this should all work - it successfully banned my test account.

**Comment by TimH96** [comment]
Can you try changing the name in the config to be all lowercase, so 'idylla' instead of 'Idylla'? 

Twitch handles all unique usernames in all lowercase but the IRC wrapper I am using is fine with both I am assuming, so when you get a new messages in your channel, it expectedly fails to hash the all lowercase one as the channels hashtable has the capital one (as configured). The error message is admittedly misleading here, finding the channel is the problem rather than accessing 'allowed_users'.

**Comment by davehamer** [comment]
Sorry for the delay, GitHub didn't notify me (or I've got the notifications going somewhere weird)
That'll teach me to not RTFM!
Missed this bit:
`Notice how it should be in all lowercase letters.`

Now works great! Thanks :)
