### ISSUE TITLE
[Feature?] Possible to read userlist rather than wait for chat message?

### ISSUE THREAD

**Issue by davehamer** [TimH96/anti-burner-bot#2]
Hey again!

Is there any way to read the userlist on a regular basis rather than waiting for a chat message? Am aware this may make a huge amount of API calls in a large channel - but with your caching of known good usernames should help after the initial rush.

We're quite a small channel and are getting this newly created burner accounts using racist, homophobic and generally unpleasant names, and then following the channel - when they follow the channel their name appears in big writing on the screen- they aren't necessarily even chatting (although a few have). It would be good if we could pre-empt this?

It's sad that people are making these accounts but anything we can do to dissuade them and make them bored of it would be good.

Cheers!
Dave

**Comment by TimH96** [comment]
I decided against doing this when first making the bot because the API options to implement this are very limited/non-existent and for normal use cases, banning on chat is sufficient.

The IRC channel itself only sends ``join`` notifications in batches, and only in smaller channels to begin with, according to [this](https://github.com/tmijs/docs/blob/gh-pages/_posts/v1.4.2/2019-03-03-Events.md#join). So a malicious user can still do their things as long as they do it within ~1 minute of joining. 

There is also no official endpoint for getting the list of users in a stream. You can use the one the webinterface uses, but it comes with it's own limitations, one of which being that it is also updated infrequently (presumably same as the IRC ``join``) according to [this](https://discuss.dev.twitch.tv/t/how-can-i-get-chat-list-in-a-channel-by-api/12225/2), so it is equally useless.

I therefore don't consider implementing this. You are of course more than welcome to fork the project to handle your case.
